### ISSUE TITLE
SitemapStream is not a constructor

### ISSUE THREAD

**Issue by akashgohel** [ekalinin/sitemap.js#318] opened 2020-07-01 13:05 UTC
I am using express with firebase function to generate dynamic sitemap.
But unfortunately got this error and return 500 error
![Screenshot from 2020-07-01 18-35-08](https://user-images.githubusercontent.com/50369580/86247115-a0ded480-bbc9-11ea-95a6-b28bcbad4198.png)
. 
SitemapStream is not a constructor

**Comment by derduher** [comment] 2020-07-01 19:23
I'm not familiar with Firebase, can you provide the version of node they are using as well as some of the code? Base on the error you've given, it sounds like you aren't importing SitemapStream

**Comment by akashgohel** [comment] 2020-07-01 21:24
Hi Patrick,
Thanks for your quick response.
The node version in firebase functions they are using is 10

Please review this code for more idea. I also imported SitemapStream

Below code is in my index.js file

/* eslint-disable no-return-assign */
/* eslint-disable eqeqeq */
/* eslint-disable one-var */
// Firebase functions

import * as functions from 'firebase-functions';

import redirectShortner from './ssr/shortner-redirect';
import discoveryRedirect from './ssr/discovery-redirect';
import viewerRedirect from './ssr/viewer-redirect';
// import generateSitemapXml from './ssr/generate-sitemap';
import addAnalyticsToDB from './ssr/analytics';

import express from 'express';
// import updateSitemap from './ssr/sitemap-update';

global.isServerSideRendered = true;

const { SitemapStream, streamToPromise } = require('sitemap')
const { createGzip } = require('zlib')

const app = express();

app.get('/discovery', discoveryRedirect);

app.get('/dekho/:projectname', viewerRedirect);
app.get('/greetings/:projectname', viewerRedirect);

// app.get('/sitemap.xml', generateSitemapXml);

// app.get('/sitemap', generateSitemapXml);
// const z = {
//   projectid: 'dekho/5b360a285e4641000f5b5678',
//   utmInfo: {
//     utm_campaign: 'orCT2018009?',
//     utm_medium: 'Direct',
//     utm_source: 'Organic'
//   }
// };

let sitemap
app.get('/sitemap', (req, res) => {
    res.header('Content-Type', 'application/xml');
    res.header('Content-Encoding', 'gzip');
    // if we have a cached entry send it
    if (sitemap) {
      res.send(sitemap)
      return
    }
  
    try {
      const smStream = new SitemapStream({ hostname: 'https://discovery.melzo.com/' })
      const pipeline = smStream.pipe(createGzip())
  
      // pipe your entries or directly write them.
      smStream.write({ url: '/page-1/',  changefreq: 'daily', priority: 0.3 })
      smStream.write({ url: '/page-2/',  changefreq: 'monthly',  priority: 0.7 })
      smStream.write({ url: '/page-3/'})    // changefreq: 'weekly',  priority: 0.5
      smStream.write({ url: '/page-4/',   img: "http://urlTest.com" })
  
      // cache the response
      streamToPromise(pipeline).then(sm => sitemap = sm)
      // make sure to attach a write stream such as streamToPromise before ending
      smStream.end()
      // stream write the response
      pipeline.pipe(res).on('error', (e) => {throw e})
    } catch (e) {
      console.error(e)
      res.status(500).end()
    }
  })
  app.get('/sitemap.xml', (req, res) => {
      res.header('Content-Type', 'application/xml');
      res.header('Content-Encoding', 'gzip');
      // if we have a cached entry send it
      if (sitemap) {
        res.send(sitemap)
        return
      }
    
      try {
        const smStream = new SitemapStream({ hostname: 'https://discovery.melzo.com/' })
        const pipeline = smStream.pipe(createGzip())
    
        // pipe your entries or directly write them.
        smStream.write({ url: '/page-1/',  changefreq: 'daily', priority: 0.3 })
        smStream.write({ url: '/page-2/',  changefreq: 'monthly',  priority: 0.7 })
        smStream.write({ url: '/page-3/'})    // changefreq: 'weekly',  priority: 0.5
        smStream.write({ url: '/page-4/',   img: "http://urlTest.com" })
    
        // cache the response
        streamToPromise(pipeline).then(sm => sitemap = sm)
        // make sure to attach a write stream such as streamToPromise before ending
        smStream.end()
        // stream write the response
        pipeline.pipe(res).on('error', (e) => {throw e})
      } catch (e) {
        console.error(e)
        res.status(500).end()
      }
    })
  
app.get('/:shortner', redirectShortner);

app.get('/**', discoveryRedirect);


export const ssrapp = functions.https.onRequest(app);
export const analytics = functions.https.onCall(addAnalyticsToDB);

**Comment by derduher** [comment] 2020-07-01 21:48
Try swapping the require for an import? `import { SitemapStream, streamToPromise } from 'sitemap';`

**Comment by derduher** [comment] 2020-07-01 21:52
If that doesn't work, I'd suggest copying one of the examples and trying to get it running locally then gradually converting it to your example above to see where it breaks.

**Comment by akashgohel** [comment] 2020-07-02 05:52
As per your suggestion, I have tried using import, but did not get any success.
For your second suggestion, I have cloned your repository and tried same code by creating a new file.
Please have a look.

// code file

const express = require('express');
const { SitemapStream, streamToPromise } = require('../dist/index');
const { createGzip } = require('zlib');

const app = express();
let sitemap;

app.get('/sitemap.xml', function (req, res) {
  res.header('Content-Type', 'application/xml');
  res.header('Content-Encoding', 'gzip');
  // if we have a cached entry send it
  if (sitemap) {
    res.send(sitemap);
    return;
  }

  try {
    const smStream = new SitemapStream({ hostname: 'https://example.com/' });
    const pipeline = smStream.pipe(createGzip());

    // pipe your entries or directly write them.
    smStream.write({ url: '/page-1/', changefreq: 'daily', priority: 0.3 });
    smStream.write({ url: '/page-2/', changefreq: 'monthly', priority: 0.7 });
    smStream.write({ url: '/page-3/' }); // changefreq: 'weekly',  priority: 0.5
    smStream.write({ url: '/page-4/', img: 'http://urlTest.com' });

    // cache the response
    streamToPromise(pipeline).then((sm) => (sitemap = sm));
    // make sure to attach a write stream such as streamToPromise before ending
    smStream.end();
    // stream write the response
    pipeline.pipe(res).on('error', (e) => {
      throw e;
    });
  } catch (e) {
    console.error(e);
    res.status(500).end();
  }
});

app.listen(3000, () => {
  console.log('listening');
});


// output generated

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
<url>
<loc>https://example.com/page-1/</loc>
<changefreq>daily</changefreq>
<priority>0.3</priority>
</url>
<url>
<loc>https://example.com/page-2/</loc>
<changefreq>monthly</changefreq>
<priority>0.7</priority>
</url>
<url>
<loc>https://example.com/page-3/</loc>
</url>
<url>
<loc>https://example.com/page-4/</loc>
<image:image>
<image:loc>http://urltest.com/</image:loc>
</image:image>
</url>
</urlset>

**Comment by derduher** [comment] 2020-07-02 05:56
There is no style info by default. It's not really meant to be read by browsers. It looks like it works when you clone it then. I'm not sure how to help you get it running in firebase without a reproducible case. You'll have to try getting it to work in a simple case with firebase and progressively modify it.

**Comment by akashgohel** [comment] 2020-07-02 05:58
Thank You Patrick,
I will sure give it a try and let you know the progress.

**Comment by akashgohel** [comment] 2020-07-02 06:55
I have set up a new firebase function from start and run it locally.
It works as expected.
Also implemented this to my existing project and deployed to firebase.
But I think the problem is with firebase.
So I have post a support ticket to firebase.
Will update you if we get any response.

**Comment by derduher** [comment] 2020-07-07 02:45
@akashgohel closing for now. Feel free to reopen.

**Closed by derduher** 2020-07-07 02:45 UTC
